version: '3.8'

services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saude
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d
    networks:
      - saude-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d saude"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço do MongoDB
  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - saude-network

  # Serviço do pgAdmin para gerenciar o PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - saude-network

# Volumes para persistir os dados
volumes:
  postgres_data:
  mongo_data:
  pgadmin_data:

# Rede para comunicação entre os contêineres
networks:
  saude-network:
    driver: bridge